### ISSUE TITLE
[BUG] Support Dark Mode

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/ml-commons-dashboards#206]
### What is the bug?
Components don't respect dark mode styles making it difficult to see

Example:
![Screenshot 2023-06-01 at 8 34 19 AM](https://github.com/opensearch-project/ml-commons-dashboards/assets/12060704/2912b45c-4250-463e-ae5d-aa42bf0dfc41)

### How can one reproduce the bug?
From dev start OSD with plugin in dark mode
```
yarn start --uiSettings.overrides["theme:darkMode"]=true --ml_commons_dashboards.enabled=true
```
or
From distribution 
```
./bin/opensearch-dashboards --uiSettings.overrides["theme:darkMode"]=true --ml_commons_dashboards.enabled=true
```

Navigate to ML plugin in OpenSearch Dashboards.

Notice input field is white.

### What is the expected behavior?
Readable in Dark Mode

### What is your host/environment?
2.8

### Do you have any screenshots?
above

### Do you have any additional context?
n/a

**Comment by wanglam** [comment]
Hi Kavilla, thank you for reporting this bug. It seems caused by the incorrect background-color for the duration picker. Will do some investigate to fix this.
