### ISSUE TITLE
[BUG] Wrong document link

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons-dashboards#208]
![Screenshot 2023-06-06 at 4 23 56 PM](https://github.com/opensearch-project/ml-commons-dashboards/assets/49084640/026a2b0c-32bb-4c64-a706-2eb230a50623)

The [Machine Learning Documentation](https://opensearch.org/docs/latest/ml-commons-plugin/ml-dashbaord/) is an invalid URL. Should change to https://opensearch.org/docs/latest/ml-commons-plugin/ml-dashboard/

**Comment by wanglam** [comment]
Hi @ylwu-amzn , Thank you for reporting this issue. This link was provided by @Naarcha-AWS at the first release of the admin UI. As I remember, there was a redirect from current URL to https://opensearch.org/docs/latest/ml-commons-plugin/ml-dashboard/ . @Naarcha-AWS Could you help me check why this redirect not work? I think we can update the link to the correct address. So we don't need to redirect anymore in the future version.
