### ISSUE TITLE
[BUG] Admin UI: no model show up when search a model

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/ml-commons-dashboards#236]
I have 50 models on a test cluster, I navigate to page 4, then search a unique model name. Then the search result page, shows "There are no results to your search. Reset the search criteria to view the deployed models."

I have to go to page1 first, then search, then can see the model.

Seems the search will also follow the same page number and that's why it shows no result.

**Comment by wanglam** [comment]
@ylwu-amzn Very appreciate for reporting this bug. I think this issue will exists in status filter. I will discuss with the dev team and try to fix it in next release.
