### ISSUE TITLE
[v2.12.0] Ensure CI/documentation reflect changes to default admin credentials

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/ml-commons-dashboards#292]
## Background
Previously, when installing the security plugin demo configuration, the cluster was spun up with the default admin credentials, `admin:admin`. A change was made in `main` and backported to `2.x` for the `2.12.0` release, which now requires an initial admin password to be passed in via the environment variable `OPENSEARCH_INITIAL_ADMIN_PASSWORD`. This will break some CI/testing that relies on OpenSearch to come up without setting this environment variable. This tracking issue is to ensure compliance with the new changes.

Coming from: https://github.com/opensearch-project/security/issues/3624

## Acceptance Criteria
 - [ ] All documentation references to the old default credentials `admin:admin` are removed
 - [ ] Ensure that CI/testing is working with `main` and `2.x` branches

**Comment by wanglam** [comment]
Hi @derek-ho , Thanks for your suggestion. We don't hard code any `admin:admin` as default credentials in our codebase. Could we marked the `All documentation references to the old default credentials admin:admin are removed` to complete? Just find there is [another PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/978) in FT repo. This PR will update credentials in `.github/workflows/release-e2e-workflow-template.yml`, the CI workflow of ml-commons-dashboards use the same template. I think the CI will be fixed after PR merged.

**Comment by derek-ho** [comment]
Hi @wanglam we have another PR out which should fix it: #981

**Comment by derek-ho** [comment]
@wanglam if the CI is working fine on 2.x/main and no credentials are present I think we can close this. Please feel free to do so, I did a quick search and didn't find anything.
