### ISSUE TITLE
[FEATURE] Support Multiple Data Source in ML Commons Dashboards Plugin

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/ml-commons-dashboards#304]
### Is your feature request related to a problem?
With multiple data source enabled, users of OpenSearch Dashboards are able to create data source connections and query local and remote OpenSearch clusters. Enabling multiple data source at dashboards plugin would ensure users that have been using the multiple data source feature to have a consistent experience in the dashboard, and allows users to use the same dashboard for different clusters.

### What solution would you like?
Support multiple data source in the ml commons dashboards plugin and allow user to use one dashboard for different backend clusters

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by BionIT** [comment]
Once https://github.com/opensearch-project/ml-commons-dashboards/pull/317 is merged, we can close this issue @wanglam

**Comment by wanglam** [comment]
The MDS has been merged to 2.x branch.
